export enum AttendanceStatus {
  CHECKED_IN = 'CHECKED_IN',
  PRESENT = 'PRESENT',
  LATE = 'LATE',
  EARLY_CHECKOUT = 'EARLY_CHECKOUT',
  MISSED_CHECKOUT = 'MISSED_CHECKOUT',
  ABSENT = 'ABSENT',
  INVALID_ATTEMPT = 'INVALID_ATTEMPT',
  REJECTED = 'REJECTED',
}
