export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  /** Attendance + workflow specific events that are not pure CRUD. */
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  ADMIN_CHECK_OUT = 'ADMIN_CHECK_OUT',
  SUBMISSION_APPROVE = 'SUBMISSION_APPROVE',
  SUBMISSION_REJECT = 'SUBMISSION_REJECT',
  DEVICE_REGISTER = 'DEVICE_REGISTER',
  DEVICE_CLEAR = 'DEVICE_CLEAR',
  DEVICE_APPROVE = 'DEVICE_APPROVE',
  AUTO_ABSENT = 'AUTO_ABSENT',
  AUTO_MISSED_CHECKOUT = 'AUTO_MISSED_CHECKOUT',
}

export enum AuditEntity {
  USER = 'USER',
  PERIOD = 'PERIOD',
  CLASS_SESSION = 'CLASS_SESSION',
  ATTENDANCE_RECORD = 'ATTENDANCE_RECORD',
  ABSENCE_SUBMISSION = 'ABSENCE_SUBMISSION',
  DEVICE = 'DEVICE',
}
